# Copyright 2021 MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.9-slim-buster
LABEL "base"="python:3.9-slim-buster"

ARG APTVER_CURL=7.64.0-4+deb10u2
ARG APTVER_TRANSPORT_HTTPS=1.8.2.2
ARG APTVER_GNUPG2=2.2.12-1+deb10u1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    apt-transport-https=${APTVER_TRANSPORT_HTTPS} \
    gnupg2=${APTVER_GNUPG2} \
    curl=${APTVER_CURL} \
    && apt-get update \
    && apt-get install --no-install-recommends -y libgssapi-krb5-2 \
    build-essential \
    unixodbc-dev

RUN python -m pip install --upgrade pip

ADD ./requirements.txt /monai_inference/requirements.txt
RUN python -m pip install -r /monai_inference/requirements.txt

ADD ./monaiinference /monai_inference/monaiinference

ENV PYTHONPATH "${PYTHONPATH}:/monai_inference/"

ENTRYPOINT ["/usr/local/bin/python", "/monai_inference/monaiinference/main.py"]
